Repository DEVRhylme-Foundation/new-website, pull requests merged in 2024-12, with the labels that each got.

#56 Updating_FeatureSection_For_Dark_Mode_Change_the_Logo
  src/components/Features/InfiniteCarousel.tsx
Labels: bug

#59 Resolved Dark Theme Partners Logos Issue
  public/images/brands/CD-dark.webp
  public/images/brands/GBS-Logo-B2.svg
  public/images/brands/IB-week-dark.png
  src/components/Clients/clientsData.tsx
Labels: bug

#60 Resolve header logo for both light and dark mode
  public/images/logo/logo.png
  public/images/logo/logo_mob.svg
  public/images/logo/logo_new.svg
  src/components/Header/index.tsx
  src/components/Header/navbar.css
Labels: bug, good first issue

#71 feat/70-Navbar-and-favicon-fix-and-updated
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
Labels: bug

#73 fix/#72-different-sections-need-correction
  markdown/blogs/event1.mdx
  markdown/blogs/event2.mdx
  markdown/blogs/event3.mdx
  src/components/Clients/clientsData.tsx
  src/components/Testimonials/SingleTestimonial.tsx
  src/components/Testimonials/index.tsx
Labels: bug

#75 feat/#74-Development-of-event-and-database-integration
  next.config.js
  package-lock.json
  package.json
  src/app/(site)/createEvent/page.tsx
  src/app/(site)/events/[eventSlug]/page.tsx
  src/app/(site)/events/page.tsx
  src/components/About/index.tsx
  src/components/Footer/index.tsx
  src/components/Team/index.tsx
  src/components/eventData/bannerEvent.tsx
  src/firebase/firebaseConfig.js
Labels: bug, enhancement

#78 fix/#76-fixed-build-error-updating-createEvent
  src/app/(site)/createEvent/page.tsx
Labels: bug

#79 fix-eliminating-all-errors
  src/app/(site)/events/page.tsx
Labels: bug

#80 fixed-complete-build
  src/firebase/firebaseConfig.js
Labels: bug
