Repository DEVRhylme-Foundation/new-website, pull requests merged in 2024-11, with the labels that each got.

#5 Update InfiniteCarousel
  src/components/Features/InfiniteCarousel.css
  src/components/Features/InfiniteCarousel.tsx
  src/components/Features/index.tsx
Labels: enhancement

#8 Update About Section
  public/images/about/about-image-01.jpg
  public/images/about/about-image-02.jpg
  public/images/about/about-image-02.webp
  src/components/About/index.tsx
  src/components/Features/index.tsx
Labels: enhancement

#20 fixing build error [BUG]
  package.json
Labels: bug

#34 fix/33-Breadcrumb.tsx_restoration
  src/app/(site)/contact/page.tsx
  src/app/(site)/events/page.tsx
  src/app/(site)/product/page.tsx
  src/components/Common/Breadcrumb.tsx
Labels: bug

#36 feat/35-add_event_cards
  package-lock.json
  package.json
  public/images/event/event1.jpeg
  src/app/(site)/events/page.tsx
  src/components/eventData/eventCard.tsx
Labels: enhancement

#38 fix/37-Responsive-event-cards
  src/app/(site)/events/page.tsx
  src/components/Header/index.tsx
  src/components/eventData/eventBanner.tsx
  src/components/eventData/eventCard.tsx
  src/components/eventData/eventStyles.css
Labels: bug

#42 fix/41-Responsiveness-fixed-in-event-banner
  src/app/(site)/events/page.tsx
  src/components/Common/ImageSlider.tsx
  src/components/eventData/bannerEvent.tsx
  src/components/eventData/eventBanner.tsx
Labels: bug

#44 feat/43-Enhanced-UI-of-event-page
  src/app/(site)/events/page.tsx
  src/components/Common/ImageSlider.tsx
  src/components/eventData/bannerEvent.tsx
  src/components/eventData/eventBanner.tsx
  src/components/eventData/eventStyles.css
Labels: enhancement

#46 feat/45-Faq-Client-Response-and-minor-content-updation
  src/app/(site)/projects/page.tsx
  src/components/CallToAction/index.tsx
  src/components/Faq/index.tsx
  src/components/Header/menuData.tsx
  src/components/Team/index.tsx
  src/components/Testimonials/index.tsx
Labels: enhancement

#48 Feat/47-added-relevant-images
  public/images/brands/Coin.png
  public/images/brands/GBS-Logo-B.png
  public/images/brands/India-Blockchain-Week.png
  public/images/brands/iblockchainM.png
  public/images/brands/img_BNB_Logo.png
  src/components/Clients/clientsData.tsx
  src/components/Header/index.tsx
Labels: enhancement

#50 Feat/49-GitHub api creation and api data population component with minor data fix
  package-lock.json
  package.json
  public/images/logo/favicon.svg
  public/images/logo/logo-icon.svg
  public/images/logo/logo-white.svg
  public/images/logo/logo.svg
  src/app/(site)/about/page.tsx
  src/app/(site)/contact/page.tsx
  src/app/(site)/error/page.tsx
  src/app/(site)/events/page.tsx
  src/app/(site)/projects/page.tsx
  src/app/api/github/route.js
  src/app/head.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/About/index.tsx
  src/components/Contact/form.tsx
  src/components/Contact/index.tsx
  src/components/Header/index.tsx
  src/components/projectData/index.tsx
  src/components/projectData/projectBanner.tsx
  src/components/projectData/projects.css
Labels: bug, documentation, enhancement

#54 feat/53-corrected navbar responsiveness and footer linking
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/Header/navbar.css
  src/components/LinkdinPosts/index.tsx
Labels: bug, enhancement
